#!/bin/bash
#title			: /etc/update-motd.d/20-cpu
#description	: This Script will output the CPU Load for each Core
#author			: SHelfinger
#date			: 20160620
#version		: 0.1    
#usage			: bash 20-cpu OR ./20-cpu
#notes			: It's colorful, be aware that some apps needs to be installed, see depencies
#bash_version	: 4.3.30(1)-release
#depencies		: mpstat (sudo apt-get install sysstat)
#				: bc (sudo apt-get install bc)
# 				: python (sudo apt-get install python)
#installation	: chmod +x 20-cpu | mv 20-cpu /etc/update-motd.d/20-cpu
#license		: GPLv3
#==============================================================================
TAB="|"
BEGIN="["
END="]"
GREP=$(which grep)
MPSTAT=$(which mpstat)
BC=$(which bc)
PYTHON=$(which python)
c=1

# mpstat has evidently changed its output format, now by default adds an extra
# column to the timestamp.  setting this fixes it.
export S_TIME_FORMAT="ISO"

$MPSTAT -P ALL | sed -n '4p' | while read output;
do 
    user=$(echo $output | awk '{print $3}' | $PYTHON -c "print(round(float(input())))")
    nice=$(echo $output | awk '{print $4}' | $PYTHON -c "print(round(float(input())))")
    system=$(echo $output | awk '{print $5}' | $PYTHON -c "print(round(float(input())))")
    iowait=$(echo $output | awk '{print $6}' | $PYTHON -c "print(round(float(input())))")
    idle=$(echo $output | awk '{print $12}')
    idles=$($BC <<< "100 - $idle")
    usep=$(echo "$idles" | $PYTHON -c "print(round(float(input())))")
    
    echo -en "\033[1;33mCPU \033[1;32mALL \033[0m(\033[01;31mLoad\033[0m/\033[0mIdle) $BEGIN"
    all=$(($user + $nice + $system + $iowait))
    free=$((100 - $all))
    drawuser=$($BC <<< "($user * 0.70 + 0.5)/1")
    drawnice=$($BC <<< "($nice * 0.70 + 0.5)/1")
    drawsys=$($BC <<< "($system * 0.70 + 0.5)/1")
    drawio=$($BC <<< "($iowait * 0.70 + 0.5)/1")
    drawall=$(($drawuser + $drawnice + $drawsys + $drawio))
    drawfree=$($BC <<< "70 - $drawall")
    for((i=0;i<$drawuser;i++)); do echo -en "\033[1;34mI"; done
    for((i=0;i<$drawnice;i++)); do echo -en "\033[1;32mI"; done
    for((i=0;i<$drawsys;i++)); do echo -en "\033[01;31mI"; done
    for((i=0;i<$drawio;i++)); do echo -en "\033[01;33mI"; done
    for((i=0;i<$drawfree;i++)); do echo -en "\033[0m "; done
    echo -en "\033[0m$END"
    echo -en " $all%/$free%\n"
done

$MPSTAT -P ALL | tail -n +5 | while read output;
do 
    user=$(echo $output | awk '{print $3}' | $PYTHON -c "print(round(float(input())))")
    nice=$(echo $output | awk '{print $4}' | $PYTHON -c "print(round(float(input())))")
    system=$(echo $output | awk '{print $5}' | $PYTHON -c "print(round(float(input())))")
    iowait=$(echo $output | awk '{print $6}' | $PYTHON -c "print(round(float(input())))")
    idle=$(echo $output | awk '{print $12}')
    idles=$($BC <<< "100 - $idle")
    usep=$(echo "$idles" | $PYTHON -c "print(round(float(input())))")
    
    echo -en "\033[1;33m     \033[1;32m$(printf %02d $c) \033[0m(\033[01;31mLoad\033[0m/\033[0mIdle) $BEGIN"
    all=$(($user + $nice + $system + $iowait))
    free=$((100 - $all))
    drawuser=$($BC <<< "($user * 0.70 + 0.5)/1")
    drawnice=$($BC <<< "($nice * 0.70 + 0.5)/1")
    drawsys=$($BC <<< "($system * 0.70 + 0.5)/1")
    drawio=$($BC <<< "($iowait * 0.70 + 0.5)/1")
    drawall=$(($drawuser + $drawnice + $drawsys + $drawio))
    drawfree=$($BC <<< "70 - $drawall")
    for((i=0;i<$drawuser;i++)); do echo -en "\033[1;34mI"; done
    for((i=0;i<$drawnice;i++)); do echo -en "\033[1;32mI"; done
    for((i=0;i<$drawsys;i++)); do echo -en "\033[01;31mI"; done
    for((i=0;i<$drawio;i++)); do echo -en "\033[01;33mI"; done
    for((i=0;i<$drawfree;i++)); do echo -en "\033[0m "; done
    echo -en "\033[0m$END"
    echo -en " $all%/$free%\n"
    ((c++))
done
